version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_URL_SHORTENER_API_BASE_URL=http://localhost:3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5275
      - FRONTEND_BASE_URL=http://localhost:3000

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"